
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/chatbot-website
    depends_on:
      - mongo
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=chatbot_website_backend.settings
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: daphne -b 0.0.0.0 -p 8000 chatbot_website_backend.asgi:application

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: chatbot-redis
    ports:
      - "6379:6379"