
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/chatbot-website
    depends_on:
      - mongo
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=chatbot_backend.settings
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: daphne -b 0.0.0.0 -p 8000 chatbot_backend.asgi:application

  frontend:
    build:
      context: chatbot_frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: chatbot-redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
      - frontend